import type { Customer } from "@/dto/dto";

export const excustomers: Customer[] = [
  { id: 1, name: "Siemens", email: "anna.kowalski@email.com" },
  { id: 2, name: "Volkswagen", email: "jan.nowak@email.com" },
  { id: 3, name: "BMW", email: "maria.lew@email.com" },
  { id: 4, name: "Mercedes-Benz", email: "piotr.z@email.com" },
  { id: 5, name: "Bosch", email: "katarzyna.s@email.com" },
  { id: 6, name: "BASF", email: "tomasz.g@email.com" },
  { id: 7, name: "Bayer", email: "ewa.d@email.com" },
  { id: 8, name: "SAP", email: "michal.k@email.com" },
  { id: 9, name: "Deutsche Bank", email: "joanna.w@email.com" },
  { id: 10, name: "Allianz", email: "robert.m@email.com" },
  { id: 11, name: "Adidas", email: "agnieszka.s@email.com" },
  { id: 12, name: "Puma", email: "krzysztof.l@email.com" },
  { id: 13, name: "L'Oreal", email: "barbara.k@email.com" },
  { id: 14, name: "Carrefour", email: "stanislaw.n@email.com" },
  { id: 15, name: "Renault", email: "elzbieta.z@email.com" },
  { id: 16, name: "Peugeot", email: "jerzy.s@email.com" },
  { id: 17, name: "TotalEnergies", email: "zofia.k@email.com" },
  { id: 18, name: "Air France", email: "lukasz.g@email.com" },
  { id: 19, name: "Société Générale", email: "marta.u@email.com" },
  { id: 20, name: "BNP Paribas", email: "andrzej.j@email.com" },
  { id: 21, name: "AXA", email: "halina.o@email.com" },
  { id: 22, name: "Santander", email: "ryszard.p@email.com" },
  { id: 23, name: "BBVA", email: "danuta.m@email.com" },
  { id: 24, name: "Telefónica", email: "henryk.s@email.com" },
  { id: 25, name: "Inditex", email: "grazyna.k@email.com" },
  { id: 26, name: "Iberdrola", email: "kazimierz.s@email.com" },
  { id: 27, name: "Eni", email: "ira.k@email.com" },
  { id: 28, name: "Enel", email: "waclaw.g@email.com" },
  { id: 29, name: "Fiat", email: "lidia.n@email.com" },
  { id: 30, name: "Pirelli", email: "boleslaw.s@email.com" },
  { id: 31, name: "Ferrero", email: "krystyna.m@email.com" },
  { id: 32, name: "Prada", email: "wieslaw.a@email.com" },
  { id: 33, name: "Gucci", email: "beata.c@email.com" },
  { id: 34, name: "Luxottica", email: "grzegorz.z@email.com" },
  { id: 35, name: "Vodafone", email: "lucyna.p@email.com" },
  { id: 36, name: "BP", email: "miroslaw.u@email.com" },
  { id: 37, name: "Shell", email: "cecylia.s@email.com" },
  { id: 38, name: "Unilever", email: "ludwik.j@email.com" },
  { id: 39, name: "Reckitt", email: "stefania.k@email.com" },
  { id: 40, name: "Tesco", email: "wlodzimierz.n@email.com" },
  { id: 41, name: "Sainsbury's", email: "irena.w@email.com" },
  { id: 42, name: "Marks & Spencer", email: "zygmunt.k@email.com" },
  { id: 43, name: "Barclays", email: "natalia.l@email.com" },
  { id: 44, name: "HSBC", email: "stefan.g@email.com" },
  { id: 45, name: "Lloyds", email: "urszula.n@email.com" },
  { id: 46, name: "GlaxoSmithKline", email: "viktor.s@email.com" },
  { id: 47, name: "AstraZeneca", email: "zofia.w@email.com" },
  { id: 48, name: "Novartis", email: "bohdan.c@email.com" },
  { id: 49, name: "Roche", email: "walentyna.s@email.com" },
  { id: 50, name: "UBS", email: "ignacy.k@email.com" },
  { id: 51, name: "Credit Suisse", email: "dorota.k@email.com" },
  { id: 52, name: "Nestlé", email: "tadeusz.p@email.com" },
  { id: 53, name: "Zurich Insurance", email: "stanisława.k@email.com" },
  { id: 54, name: "Swatch", email: "czeslaw.m@email.com" },
  { id: 55, name: "Heineken", email: "leokadia.z@email.com" },
  { id: 56, name: "Philips", email: "edmund.g@email.com" },
  { id: 57, name: "ING", email: "felicja.n@email.com" },
  { id: 58, name: "ABN AMRO", email: "franciszek.k@email.com" },
  { id: 59, name: "KPN", email: "gerarda.z@email.com" },
  { id: 60, name: "AkzoNobel", email: "gustaw.s@email.com" },
  { id: 61, name: "ASML", email: "henryka.l@email.com" },
  { id: 62, name: "Randstad", email: "hilary.s@email.com" },
  { id: 63, name: "KLM", email: "ignatia.w@email.com" },
  { id: 64, name: "Anheuser-Busch InBev", email: "izabella.z@email.com" },
  { id: 65, name: "Solvay", email: "joachim.k@email.com" },
  { id: 66, name: "Umicore", email: "joanna.c@email.com" },
  { id: 67, name: "ArcelorMittal", email: "joanna.kar@email.com" },
  { id: 68, name: "RTL Group", email: "jolanta.b@email.com" },
  { id: 69, name: "Sonae", email: "jozef.s@email.com" },
  { id: 70, name: "Galp", email: "judyta.s@email.com" },
  { id: 71, name: "Jerónimo Martins", email: "julian.g@email.com" },
  { id: 72, name: "EDP", email: "justyna.k@email.com" },
  { id: 73, name: "CRH", email: "kafia.l@email.com" },
  { id: 74, name: "Ryanair", email: "kalina.m@email.com" },
  { id: 75, name: "Kerry Group", email: "kamila.s@email.com" },
  { id: 76, name: "Smurfit Kappa", email: "karol.z@email.com" },
  { id: 77, name: "Telecom Italia", email: "karolina.z@email.com" },
  { id: 78, name: "UniCredit", email: "kasimiera.p@email.com" },
  { id: 79, name: "Intesa Sanpaolo", email: "katarzyna.a@email.com" },
  { id: 80, name: "Lidl", email: "kazimierz.j@email.com" },
  { id: 81, name: "Aldi", email: "ketura.s@email.com" },
  { id: 82, name: "Metro", email: "kordian.g@email.com" },
  { id: 83, name: "Kaufland", email: "kornelia.w@email.com" },
  { id: 84, name: "CaixaBank", email: "korneliusz.s@email.com" },
  { id: 85, name: "Dassault", email: "krzysztof.k@email.com" },
  { id: 86, name: "Thales", email: "krystyna.g@email.com" },
  { id: 87, name: "Capgemini", email: "kunegunda.p@email.com" },
  { id: 88, name: "Accor", email: "lejba.o@email.com" },
  { id: 89, name: "E.ON", email: "leonia.m@email.com" },
  { id: 90, name: "RWE", email: "leopold.w@email.com" },
  { id: 91, name: "Thyssenkrupp", email: "leontyna.z@email.com" },
  { id: 92, name: "Merck KGaA", email: "lidia.s@email.com" },
  { id: 93, name: "Zalando", email: "lilia.m@email.com" },
  { id: 94, name: "Delivery Hero", email: "liliana.z@email.com" },
  { id: 95, name: "Booking.com", email: "liubov.s@email.com" },
  { id: 96, name: "Just Eat Takeaway", email: "lizy.b@email.com" },
  { id: 97, name: "Ocado", email: "lucja.s@email.com" },
  { id: 98, name: "Next plc", email: "lukasz.a@email.com" },
  { id: 99, name: "Securitas (EU)", email: "magda.t@email.com" },
  { id: 100, name: "Miele", email: "magdalena.p@email.com" },
];
