import type { ICASOCNT } from "@/CustomerSearchList";
import type { ICASOINV } from "@/dto/dto";

export const excustomers: ICASOCNT[] = [
  {
    NAACOM: "anna.kowalski",
    NANUM: "1234",
    NANAME: "Siemens",
    NAEMAIL: "maciej.ozdzinski@clarior.be",
  },
  {
    NAACOM: "jan.nowak",
    NANUM: "56789",
    NANAME: "Volkswagen",
    NAEMAIL: "maciej.ozdzinski@clarior.be",
  },
  {
    NAACOM: "maria.lew",
    NANUM: "345678",
    NANAME: "BMW",
    NAEMAIL: "maciej.ozdzinski@clarior.be",
  },
  {
    NAACOM: "piotr.z",
    NANUM: "1234567",
    NANAME: "Mercedes-Benz",
    NAEMAIL: "Piotr.popek@clarior.be",
  },
  {
    NAACOM: "katarzyna.s",
    NANUM: "89012345",
    NANAME: "Bosch",
    NAEMAIL: "maciej.ozdzinski@clarior.be",
  },
  {
    NAACOM: "pawel.k",
    NANUM: "678901234",
    NANAME: "Philips",
    NAEMAIL: "pawel.kowalczyk@philips.com",
  },
  {
    NAACOM: "agnieszka.r",
    NANUM: "234567890",
    NANAME: "Oracle",
    NAEMAIL: "agnieszka.rozanska@oracle.com",
  },
  {
    NAACOM: "tomasz.m",
    NANUM: "4567890",
    NANAME: "Microsoft",
    NAEMAIL: "tomasz.marcinkowski@microsoft.com",
  },
  {
    NAACOM: "ewelina.b",
    NANUM: "78901234",
    NANAME: "Google",
    NAEMAIL: "ewelina.borowska@google.com",
  },
  {
    NAACOM: "michal.g",
    NANUM: "890123456",
    NANAME: "Amazon",
    NAEMAIL: "michal.grzelak@amazon.com",
  },
  {
    NAACOM: "anna.p",
    NANUM: "1234567890",
    NANAME: "Apple",
    NAEMAIL: "anna.piotrowska@apple.com",
  },
  {
    NAACOM: "lukasz.s",
    NANUM: "2345",
    NANAME: "Intel",
    NAEMAIL: "lukasz.szymanski@intel.com",
  },
  {
    NAACOM: "olga.w",
    NANUM: "67890",
    NANAME: "AMD",
    NAEMAIL: "olga.wisniewska@amd.com",
  },
  {
    NAACOM: "sebastian.c",
    NANUM: "123456",
    NANAME: "Samsung",
    NAEMAIL: "sebastian.czerwinski@samsung.com",
  },
  {
    NAACOM: "karolina.l",
    NANUM: "7890123",
    NANAME: "LG",
    NAEMAIL: "karolina.lewandowska@lg.com",
  },
  {
    NAACOM: "grzegorz.t",
    NANUM: "45678901",
    NANAME: "ABB",
    NAEMAIL: "grzegorz.tomaszewski@abb.com",
  },
  {
    NAACOM: "monika.n",
    NANUM: "2345678",
    NANAME: "Schneider Electric",
    NAEMAIL: "monika.nowak@se.com",
  },
  {
    NAACOM: "marcin.f",
    NANUM: "8901234",
    NANAME: "Honeywell",
    NAEMAIL: "marcin.filipowicz@honeywell.com",
  },
  {
    NAACOM: "iwona.k",
    NANUM: "5678901",
    NANAME: "Hitachi",
    NAEMAIL: "iwona.kowal@hitachi.com",
  },
  {
    NAACOM: "dariusz.p",
    NANUM: "12345678",
    NANAME: "Toshiba",
    NAEMAIL: "dariusz.przybysz@toshiba.com",
  },
  {
    NAACOM: "dorota.s",
    NANUM: "234567",
    NANAME: "Fujitsu",
    NAEMAIL: "dorota.sobczak@fujitsu.com",
  },
  {
    NAACOM: "mateusz.j",
    NANUM: "8901234",
    NANAME: "Panasonic",
    NAEMAIL: "mateusz.jablonski@panasonic.com",
  },
  {
    NAACOM: "anna.g",
    NANUM: "456789",
    NANAME: "SAP",
    NAEMAIL: "anna.gorska@sap.com",
  },
  {
    NAACOM: "krzysztof.b",
    NANUM: "1234567",
    NANAME: "Deloitte",
    NAEMAIL: "krzysztof.baran@deloitte.com",
  },
  {
    NAACOM: "julita.m",
    NANUM: "890123",
    NANAME: "Accenture",
    NAEMAIL: "julita.michalowska@accenture.com",
  },
  {
    NAACOM: "patryk.z",
    NANUM: "6789012",
    NANAME: "KPMG",
    NAEMAIL: "patryk.zalewski@kpmg.com",
  },
  {
    NAACOM: "magdalena.o",
    NANUM: "123456789",
    NANAME: "PwC",
    NAEMAIL: "magdalena.olczyk@pwc.com",
  },
  {
    NAACOM: "rafal.r",
    NANUM: "2345678901",
    NANAME: "EY",
    NAEMAIL: "rafal.romanowicz@ey.com",
  },
  {
    NAACOM: "ewa.s",
    NANUM: "3456789",
    NANAME: "Capgemini",
    NAEMAIL: "ewa.stanislawska@capgemini.com",
  },
  {
    NAACOM: "konrad.l",
    NANUM: "4567890",
    NANAME: "Cisco",
    NAEMAIL: "konrad.lewandowski@cisco.com",
  },
  {
    NAACOM: "kamil.u",
    NANUM: "5678901",
    NANAME: "Nokia",
    NAEMAIL: "kamil.urbanski@nokia.com",
  },
  {
    NAACOM: "agnieszka.k",
    NANUM: "6789012",
    NANAME: "Ericsson",
    NAEMAIL: "agnieszka.kaczmarek@ericsson.com",
  },
  {
    NAACOM: "tomek.h",
    NANUM: "7890123",
    NANAME: "Huawei",
    NAEMAIL: "tomek.holub@huawei.com",
  },
  {
    NAACOM: "beata.p",
    NANUM: "8901234",
    NANAME: "Siemens Energy",
    NAEMAIL: "beata.pawlowska@siemens-energy.com",
  },
  {
    NAACOM: "lukasz.d",
    NANUM: "12345678",
    NANAME: "Volvo",
    NAEMAIL: "lukasz.dabrowski@volvo.com",
  },
  {
    NAACOM: "anna.r",
    NANUM: "23456789",
    NANAME: "Renault",
    NAEMAIL: "anna.rokicka@renault.com",
  },
  {
    NAACOM: "pawel.s",
    NANUM: "3456789",
    NANAME: "Peugeot",
    NAEMAIL: "pawel.sobczak@peugeot.com",
  },
  {
    NAACOM: "marta.c",
    NANUM: "4567890",
    NANAME: "Continental",
    NAEMAIL: "marta.czajkowska@continental.com",
  },
];

export const sampleInvoices: ICASOINV[] = [
  {
    DTACOM: "2025-01-03",
    DTREFX: 100001,
    DTDOTY: "FAK",
    DTIDNO: 1,
    DTTTXT: "Invoice for January sale",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-05",
    DTREFX: 100002,
    DTDOTY: "FAK",
    DTIDNO: 2,
    DTTTXT: "Invoice — subscription renewal",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-08",
    DTREFX: 100003,
    DTDOTY: "CRN", // Credit note
    DTIDNO: 3,
    DTTTXT: "Credit note for returned items",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-12",
    DTREFX: 100004,
    DTDOTY: "FAK",
    DTIDNO: 4,
    DTTTXT: "Invoice for consulting services",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-14",
    DTREFX: 100005,
    DTDOTY: "PRF", // Proforma
    DTIDNO: 5,
    DTTTXT: "Proforma for upcoming order",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-15",
    DTREFX: 100006,
    DTDOTY: "FAK",
    DTIDNO: 6,
    DTTTXT: "Invoice — equipment delivery",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-18",
    DTREFX: 100007,
    DTDOTY: "FAK",
    DTIDNO: 7,
    DTTTXT: "Invoice — software license",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-19",
    DTREFX: 100008,
    DTDOTY: "CRN",
    DTIDNO: 8,
    DTTTXT: "Credit note for overpayment",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-22",
    DTREFX: 100009,
    DTDOTY: "FAK",
    DTIDNO: 9,
    DTTTXT: "Invoice — hardware subscription",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-25",
    DTREFX: 100010,
    DTDOTY: "PRF",
    DTIDNO: 10,
    DTTTXT: "Proforma for future services",
    DLPIDS: [],
  },

  {
    DTACOM: "2025-01-27",
    DTREFX: 100011,
    DTDOTY: "FAK",
    DTIDNO: 11,
    DTTTXT: "Invoice — spare parts delivery",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-28",
    DTREFX: 100012,
    DTDOTY: "PRF",
    DTIDNO: 12,
    DTTTXT: "Proforma — machinery upgrade offer",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-01-30",
    DTREFX: 100013,
    DTDOTY: "CRN",
    DTIDNO: 13,
    DTTTXT: "Credit note — incorrect VAT rate",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-02-01",
    DTREFX: 100014,
    DTDOTY: "FAK",
    DTIDNO: 14,
    DTTTXT: "Invoice — SaaS monthly subscription",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-02-04",
    DTREFX: 100015,
    DTDOTY: "PRF",
    DTIDNO: 15,
    DTTTXT: "Proforma — new full-year contract",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-02-05",
    DTREFX: 100016,
    DTDOTY: "FAK",
    DTIDNO: 16,
    DTTTXT: "Invoice — IT security package",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-02-06",
    DTREFX: 100017,
    DTDOTY: "FAK",
    DTIDNO: 17,
    DTTTXT: "Invoice — production support",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-02-07",
    DTREFX: 100018,
    DTDOTY: "CRN",
    DTIDNO: 18,
    DTTTXT: "Credit note — returned spare parts",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-02-10",
    DTREFX: 100019,
    DTDOTY: "FAK",
    DTIDNO: 19,
    DTTTXT: "Invoice — R&D consulting",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-02-11",
    DTREFX: 100020,
    DTDOTY: "FAK",
    DTIDNO: 20,
    DTTTXT: "Invoice — new corporate devices",
    DLPIDS: [],
  },
  {
    DTACOM: "2025-02-13",
    DTREFX: 100021,
    DTDOTY: "PRF",
    DTIDNO: 21,
    DTTTXT: "Proforma — planned implementation project",
    DLPIDS: [],
  },
];
